dcp-855-error-handling-when-accession-is-not-found
ebi-ait/geo_to_hca pull request #39
Opened 2022-09-16 13:51 UTC by amnonkhen

2022-09-26 09:58 UTC, ESapenaVentura requested changes
small comment on config class

2022-09-28 10:13 UTC, amnonkhen commented on geo_to_hca/config.py
> +                  ''
1. `Config` can accept strings as well as booleans.
2. a careless keypress, probably.

2022-09-28 10:44 UTC, MightyAx commented on geo_to_hca/utils/sra_utils.py
> +        raise RuntimeError(f'cannot build the srp_metadata from {efetch_request.url}: '
Should we throw a more specific exception here?

2022-09-28 10:44 UTC, MightyAx commented on geo_to_hca/utils/sra_utils.py
> +        raise ValueError(f'unsupported accession_type: {accession_type}')
Should we throw a more specific exception here?

2022-10-03 08:45 UTC, merged